In [8]:
import pandas as pd
df_2020 = pd.read_csv('/content/drive/MyDrive/datasets_queimadas/bdqueimadas_2020-01-01_2021-01-01.csv')
df_2021 = pd.read_csv('/content/drive/MyDrive/datasets_queimadas/bdqueimadas_2021-01-01_2022-01-01.csv')
df_2022 = pd.read_csv('/content/drive/MyDrive/datasets_queimadas/bdqueimadas_2022-01-01_2023-01-01.csv')
df_2023 = pd.read_csv('/content/drive/MyDrive/datasets_queimadas/bdqueimadas_2022-01-01_2023-01-01.csv')
csv_files = [df_2020, df_2021, df_2022, df_2023]
df_combinado = pd.concat(csv_files, ignore_index=True)
df_combinado.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 18721184 entries, 0 to 18721183
Data columns (total 12 columns):
 #   Column        Dtype
---  ------        -----
 0   DataHora      object
 1   Satelite      object
 2   Pais          object
 3   Estado        object
 4   Municipio     object
 5   Bioma         object
 6   DiaSemChuva   float64
 7   Precipitacao  float64
 8   RiscoFogo     float64
 9   FRP           float64
 10  Latitude      float64
 11  Longitude     float64
dtypes: float64(6), object(6)
memory usage: 1.7+ GB

Limpeza de dados

In [14]:
print("Valores nulos por coluna:",df_combinado.isnull().sum())

df_combinado['DiaSemChuva'] = df_combinado['DiaSemChuva'].fillna(0)
df_combinado['Precipitacao'] = df_combinado['Precipitacao'].fillna(0)
df_combinado['RiscoFogo'] = df_combinado['RiscoFogo'].fillna(0)
df_combinado['FRP'] = df_combinado['FRP'].fillna(0)

print("Valores nulos por coluna:",df_combinado.isnull().sum())

df_combinado = df_combinado.drop_duplicates()
print("Valores duplicados por coluna:",df_combinado.duplicated().sum())

Valores nulos por coluna: DataHora              0
Estado                0
Bioma                58
DiaSemChuva           0
Precipitacao          0
RiscoFogo             0
FRP             5168306
Latitude              0
Longitude             0
dtype: int64
Valores nulos por coluna: DataHora         0
Estado           0
Bioma           58
DiaSemChuva      0
Precipitacao     0
RiscoFogo        0
FRP              0
Latitude         0
Longitude        0
dtype: int64
Valores duplicados por coluna: 0

0           Mata Atlântica
1           Mata Atlântica
2           Mata Atlântica
3           Mata Atlântica
4           Mata Atlântica
                 ...
14158522          Amazônia
14158523          Amazônia
14158524    Mata Atlântica
14158525           Cerrado
14158526           Cerrado
Name: Bioma, Length: 14154512, dtype: object

In [ ]:
#padronização
df_combinado['Estado'].str.strip()
df_combinado['Bioma'].str.strip()

In [10]:
df_combinado = df_combinado.drop_duplicates()
print("Valores duplicados por coluna:",df_combinado.duplicated().sum())

Valores duplicados por coluna: 0
Valores duplicados por coluna: 0

In [ ]:
df_combinado['DataHora'] = pd.to_datetime(df_combinado['DataHora'], format='%d/%m/%Y %H:%M:%S')

In [15]:
#colunas para remover
colunas_para_remover = ['Pais', 'Municipio', 'Satelite']
df_combinado = df_combinado.drop(columns=[col for col in colunas_para_remover if col in df_combinado.columns])
display(df_combinado.head())

,DataHora,Estado,Bioma,DiaSemChuva,Precipitacao,RiscoFogo,FRP,Latitude,Longitude
0,2020/01/01 00:45:28,PARANÁ,Mata Atlântica,11.0,3.3,0.2,0.0,-25.187599,-49.393501
1,﻿2020/01/01 00:45:28,PARANÁ,Mata Atlântica,11.0,3.2,0.2,0.0,-25.185699,-49.383202
2,2020/01/01 00:45:53,PARANÁ,Mata Atlântica,11.0,3.4,0.2,0.0,-25.225500,-49.385201
3,2020/01/01 00:45:53,PARANÁ,Mata Atlântica,11.0,3.3,0.2,0.0,-25.223600,-49.374901
4,2020/01/01 00:45:54,RIO DE JANEIRO,Mata Atlântica,7.0,0.8,1.0,0.0,-22.473801,-44.118999